name: Go Gating

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'stable', 'oldstable' ]
    name: Go ${{ matrix.go }} - Run Program
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go run main.go